version: '3.7'
services:
  nginx:
    build: ./requirements/nginx/.
    restart: always
    image: nginx
    container_name: "nginx_container"
    depends_on:
      - wordpress
    init: true
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/wordpress
    networks:
      - my_net
  maria-db:
    build: ./requirements/mariadb/.
    image: maria-db
    restart: always
    container_name: "mariaDB_container"
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - my_net
    init: true
  wordpress:
    init: true
    build: ./requirements/wordpress/.
    restart: always
    depends_on:
      - redis
      - maria-db
    volumes:
      - wp:/var/www/wordpress
    image: wordpress
    container_name: "wp_container"
    env_file:
      - .env
    networks:
      - my_net
  static_website:
    init: true
    build: ./requirements/bonus/website/.
    restart: always
    ports:
      - "9090:9090"
    image: static_website
    container_name: "static_website_container"
    env_file:
      - .env
    networks:
      - my_net
  phpmyadmin:
    init: true
    build:
      context: ./requirements/bonus/phpmyadmin/.
      dockerfile: Dockerfile
    image: phpmyadmin
    container_name: "phpmyadmin_container"
    restart: always
    env_file:
      - .env
    ports:
      - "9092:9092"
    networks:
      - my_net
  redis:
    init: true
    build: ./requirements/bonus/redis/.
    container_name: redis_container
    restart: always
    image: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - my_net
  adminer:
    init: true
    build:
      context: ./requirements/bonus/adminer/.
      dockerfile: Dockerfile
    container_name: adminer_container
    image: adminer
    depends_on:
      - maria-db
    ports:
      - "9093:9093"
    env_file:
      - .env
    networks:
      - my_net
    restart: always

volumes:
  wp:
    driver: local
    driver_opts:
      device: /home/mel-amma/data/wp
      o: bind
      type: none
  db:
    driver: local
    driver_opts:
      device: /home/mel-amma/data/db
      o: bind
      type: none
  redis:
    driver: local
    driver_opts:
      device: /home/mel-amma/data/redis
      o: bind
      type: none
networks:
  my_net: